// PLANO ANUAL DE LEITURA DA BÍBLIA CATÓLICA AVE MARIA - 365 DIAS (73 LIVROS COMPLETOS)

export const MONTH_NAMES = {
  pt: ['Janeiro', 'Fevereiro', 'Março', 'Abril', 'Maio', 'Junho', 'Julho', 'Agosto', 'Setembro', 'Outubro', 'Novembro', 'Dezembro'],
  en: ['January', 'February', 'March', 'April', 'May', 'June', 'July', 'August', 'September', 'October', 'November', 'December'],
  es: ['Enero', 'Febrero', 'Marzo', 'Abril', 'Mayo', 'Junio', 'Julio', 'Agosto', 'Septiembre', 'Octubre', 'Noviembre', 'Diciembre']
};

export const CATHOLIC_PLAN_DAYS = [
  // ==========================================
  // MÊS 1 (JANEIRO): DIAS 1 A 31
  // Gênesis (1-50) & São Mateus (1-28)
  // ==========================================
  { day: 1, month: 1, title: 'A Criação e o Início da Fé', read: 'Gênesis 1-2 • São Mateus 1', bookId: 'gn', chapter: 1 },
  { day: 2, month: 1, title: 'A Queda e a Promessa da Redenção', read: 'Gênesis 3-4 • São Mateus 2', bookId: 'gn', chapter: 3 },
  { day: 3, month: 1, title: 'A Arca e a Aliança de Noé', read: 'Gênesis 5-7 • São Mateus 3', bookId: 'gn', chapter: 5 },
  { day: 4, month: 1, title: 'O Arco-Íris e as Primeiras Nações', read: 'Gênesis 8-10 • São Mateus 4', bookId: 'gn', chapter: 8 },
  { day: 5, month: 1, title: 'A Torre de Babel e a Vocação de Abrão', read: 'Gênesis 11-13 • São Mateus 5', bookId: 'gn', chapter: 11 },
  { day: 6, month: 1, title: 'Melquisedec e a Aliança com Abrão', read: 'Gênesis 14-16 • São Mateus 6', bookId: 'gn', chapter: 14 },
  { day: 7, month: 1, title: 'A Circuncisão e os Três Visitantes', read: 'Gênesis 17-18 • São Mateus 7', bookId: 'gn', chapter: 17 },
  { day: 8, month: 1, title: 'A Provação de Sodoma e o Nascimento de Isaac', read: 'Gênesis 19-21 • São Mateus 8', bookId: 'gn', chapter: 19 },
  { day: 9, month: 1, title: 'O Sacrifício de Isaac no Monte Moriá', read: 'Gênesis 22-23 • São Mateus 9', bookId: 'gn', chapter: 22 },
  { day: 10, month: 1, title: 'Rebeca, Isaac e a Bênção Familiar', read: 'Gênesis 24-25 • São Mateus 10', bookId: 'gn', chapter: 24 },
  { day: 11, month: 1, title: 'Jacó, Esaú e o Sonho da Escada Celestial', read: 'Gênesis 26-28 • São Mateus 11', bookId: 'gn', chapter: 26 },
  { day: 12, month: 1, title: 'Jacó, Labão, Lia e Raquel', read: 'Gênesis 29-30 • São Mateus 12', bookId: 'gn', chapter: 29 },
  { day: 13, month: 1, title: 'A Luta de Jacó com o Anjo no Jaboque', read: 'Gênesis 31-32 • São Mateus 13', bookId: 'gn', chapter: 31 },
  { day: 14, month: 1, title: 'O Reencontro com Esaú e a Volta a Betel', read: 'Gênesis 33-35 • São Mateus 14', bookId: 'gn', chapter: 33 },
  { day: 15, month: 1, title: 'Os Sonhos de José e a Túnica Colorida', read: 'Gênesis 36-37 • São Mateus 15', bookId: 'gn', chapter: 36 },
  { day: 16, month: 1, title: 'José na Prisão e os Sonhos no Egito', read: 'Gênesis 38-40 • São Mateus 16', bookId: 'gn', chapter: 38 },
  { day: 17, month: 1, title: 'José diante do Faraó e os Sete Anos de Fartura', read: 'Gênesis 41-42 • São Mateus 17', bookId: 'gn', chapter: 41 },
  { day: 18, month: 1, title: 'Os Irmãos de José no Egito e a Taça de Prata', read: 'Gênesis 43-44 • São Mateus 18', bookId: 'gn', chapter: 43 },
  { day: 19, month: 1, title: 'A Revelação de José e a Chegada de Jacó', read: 'Gênesis 45-47 • São Mateus 19', bookId: 'gn', chapter: 45 },
  { day: 20, month: 1, title: 'A Bênção das Doze Tribos e a Esperança Messiânica', read: 'Gênesis 48-50 • São Mateus 20', bookId: 'gn', chapter: 48 },
  { day: 21, month: 1, title: 'A Entrada Triunfal e a Purificação do Templo', read: 'Salmos 1-2 • São Mateus 21', bookId: 'mt', chapter: 21 },
  { day: 22, month: 1, title: 'O Banquete Nupcial e o Maior Mandamento', read: 'Salmos 3-4 • São Mateus 22', bookId: 'mt', chapter: 22 },
  { day: 23, month: 1, title: 'As Advertências aos Fariseus', read: 'Salmos 5-6 • São Mateus 23', bookId: 'mt', chapter: 23 },
  { day: 24, month: 1, title: 'O Sermão Escatológico e a Vigilância', read: 'Salmos 7-8 • São Mateus 24', bookId: 'mt', chapter: 24 },
  { day: 25, month: 1, title: 'As Virgens Prudentes e os Talentos', read: 'Salmos 9-10 • São Mateus 25', bookId: 'mt', chapter: 25 },
  { day: 26, month: 1, title: 'A Última Ceia e a Oração no Getsêmani', read: 'Salmos 11-12 • São Mateus 26', bookId: 'mt', chapter: 26 },
  { day: 27, month: 1, title: 'A Paixão, Crucificação e Morte do Senhor', read: 'Salmos 13-14 • São Mateus 27', bookId: 'mt', chapter: 27 },
  { day: 28, month: 1, title: 'A Ressurreição e a Grande Comissão Apostólica', read: 'Salmos 15-16 • São Mateus 28', bookId: 'mt', chapter: 28 },
  { day: 29, month: 1, title: 'Louvor ao Deus Libertador', read: 'Salmos 17-18 • Provérbios 1', bookId: 'sl', chapter: 17 },
  { day: 30, month: 1, title: 'A Lei do Senhor e a Sabedoria Celestial', read: 'Salmos 19-20 • Provérbios 2', bookId: 'sl', chapter: 19 },
  { day: 31, month: 1, title: 'A Oração do Justo e a Confiança Inabalável', read: 'Salmos 21-22 • Provérbios 3', bookId: 'sl', chapter: 21 },

  // ==========================================
  // MÊS 2 (FEVEREIRO): DIAS 32 A 59
  // Êxodo (1-40), Levítico (1-27) & São Marcos (1-16)
  // ==========================================
  { day: 32, month: 2, title: 'A Servidão no Egito e o Nascimento de Moisés', read: 'Êxodo 1-3 • São Marcos 1', bookId: 'ex', chapter: 1 },
  { day: 33, month: 2, title: 'A Sarça Ardente e o Nome de Deus (Eu Sou)', read: 'Êxodo 4-6 • São Marcos 2', bookId: 'ex', chapter: 4 },
  { day: 34, month: 2, title: 'As Pragas no Egito e o Braço Forte do Senhor', read: 'Êxodo 7-9 • São Marcos 3', bookId: 'ex', chapter: 7 },
  { day: 35, month: 2, title: 'A Páscoa Judaica e a Noite da Libertação', read: 'Êxodo 10-12 • São Marcos 4', bookId: 'ex', chapter: 10 },
  { day: 36, month: 2, title: 'A Passagem do Mar Vermelho e o Cântico de Maria', read: 'Êxodo 13-15 • São Marcos 5', bookId: 'ex', chapter: 13 },
  { day: 37, month: 2, title: 'O Maná do Céu, a Água da Rocha e Jetro', read: 'Êxodo 16-18 • São Marcos 6', bookId: 'ex', chapter: 16 },
  { day: 38, month: 2, title: 'O Monte Sinai e os Dez Mandamentos da Aliança', read: 'Êxodo 19-21 • São Marcos 7', bookId: 'ex', chapter: 19 },
  { day: 39, month: 2, title: 'As Leis Santas e o Anjo que Conduz o Povo', read: 'Êxodo 22-24 • São Marcos 8', bookId: 'ex', chapter: 22 },
  { day: 40, month: 2, title: 'A Arca da Aliança e as Instruções do Tabernáculo', read: 'Êxodo 25-27 • São Marcos 9', bookId: 'ex', chapter: 25 },
  { day: 41, month: 2, title: 'As Vestes Sacerdotais de Aarão e o Altar do Incenso', read: 'Êxodo 28-30 • São Marcos 10', bookId: 'ex', chapter: 28 },
  { day: 42, month: 2, title: 'O Bezerro de Ouro e a Intercessão de Moisés', read: 'Êxodo 31-33 • São Marcos 11', bookId: 'ex', chapter: 31 },
  { day: 43, month: 2, title: 'A Glória do Senhor e a Renovação das Tábuas', read: 'Êxodo 34-36 • São Marcos 12', bookId: 'ex', chapter: 34 },
  { day: 44, month: 2, title: 'A Construção do Tabernáculo e a Nuvem da Glória', read: 'Êxodo 37-40 • São Marcos 13', bookId: 'ex', chapter: 37 },
  { day: 45, month: 2, title: 'A Ceia Pascal e o Julgamento de Jesus', read: 'Levítico 1-3 • São Marcos 14', bookId: 'mc', chapter: 14 },
  { day: 46, month: 2, title: 'A Morte na Cruz e a Glória da Ressurreição', read: 'Levítico 4-6 • São Marcos 15-16', bookId: 'mc', chapter: 15 },
  { day: 47, month: 2, title: 'A Consagração dos Sacerdotes e as Ofertas Santas', read: 'Levítico 7-9 • Salmos 24', bookId: 'lv', chapter: 7 },
  { day: 48, month: 2, title: 'O Fogo Sagrado e as Leis de Pureza', read: 'Levítico 10-12 • Salmos 25', bookId: 'lv', chapter: 10 },
  { day: 49, month: 2, title: 'A Cura da Lepra e a Purificação do Povo', read: 'Levítico 13-15 • Salmos 26', bookId: 'lv', chapter: 13 },
  { day: 50, month: 2, title: 'O Dia do Perdão (Yom Kippur) e o Sangue da Aliança', read: 'Levítico 16-18 • Salmos 28', bookId: 'lv', chapter: 16 },
  { day: 51, month: 2, title: 'Sede Santos porque Eu Sou Santo: A Lei do Amor', read: 'Levítico 19-21 • Salmos 29', bookId: 'lv', chapter: 19 },
  { day: 52, month: 2, title: 'As Festas do Senhor: Páscoa, Pentecostes e Tabernáculos', read: 'Levítico 22-24 • Salmos 30', bookId: 'lv', chapter: 22 },
  { day: 53, month: 2, title: 'O Ano Jubilar, as Bênçãos e a Fidelidade a Deus', read: 'Levítico 25-27 • Salmos 31', bookId: 'lv', chapter: 25 },
  { day: 54, month: 2, title: 'O Censo no Deserto de Sinai e as Tribos de Israel', read: 'Números 1-3 • Salmos 33', bookId: 'nm', chapter: 1 },
  { day: 55, month: 2, title: 'O Serviço dos Levitas e o Voto de Nazireu', read: 'Números 4-6 • Salmos 34', bookId: 'nm', chapter: 4 },
  { day: 56, month: 2, title: 'A Bênção Sacerdotal e a Dedicação do Altar', read: 'Números 7-9 • Salmos 35', bookId: 'nm', chapter: 7 },
  { day: 57, month: 2, title: 'A Coluna de Fogo e a Partida do Sinai', read: 'Números 10-12 • Salmos 36', bookId: 'nm', chapter: 10 },
  { day: 58, month: 2, title: 'Os Doze Espias em Canaã e a Fé de Josué e Caleb', read: 'Números 13-15 • Salmos 37', bookId: 'nm', chapter: 13 },
  { day: 59, month: 2, title: 'A Rebelião de Coré e a Vara Florida de Aarão', read: 'Números 16-18 • Salmos 38', bookId: 'nm', chapter: 16 },

  // ==========================================
  // MÊS 3 (MARÇO): DIAS 60 A 90
  // Números (19-36), Deuteronômio (1-34) & São Lucas (1-24)
  // ==========================================
  { day: 60, month: 3, title: 'A Água de Meriba, a Serpente de Bronze e Balaão', read: 'Números 19-21 • São Lucas 1', bookId: 'nm', chapter: 19 },
  { day: 61, month: 3, title: 'A Anunciação e o Magnificat de Maria', read: 'Números 22-24 • São Lucas 2', bookId: 'lc', chapter: 1 },
  { day: 62, month: 3, title: 'O Segundo Censo e a Escolha de Josué', read: 'Números 25-27 • São Lucas 3', bookId: 'nm', chapter: 25 },
  { day: 63, month: 3, title: 'As Leis de Herança e a Vitória sobre Madiã', read: 'Números 28-31 • São Lucas 4', bookId: 'nm', chapter: 28 },
  { day: 64, month: 3, title: 'As Cidades de Refúgio e os Limites da Terra Prometida', read: 'Números 32-36 • São Lucas 5', bookId: 'nm', chapter: 32 },
  { day: 65, month: 3, title: 'Moisés Lembra a Peregrinação no Deserto', read: 'Deuteronômio 1-3 • São Lucas 6', bookId: 'dt', chapter: 1 },
  { day: 66, month: 3, title: 'Ouve, ó Israel (Shemá) e a Fidelidade à Palavra', read: 'Deuteronômio 4-6 • São Lucas 7', bookId: 'dt', chapter: 4 },
  { day: 67, month: 3, title: 'O Povo Escolhido e a Advertência contra o Orgulho', read: 'Deuteronômio 7-9 • São Lucas 8', bookId: 'dt', chapter: 7 },
  { day: 68, month: 3, title: 'Circuncidai o Vosso Coração: A Lei do Amor', read: 'Deuteronômio 10-12 • São Lucas 9', bookId: 'dt', chapter: 10 },
  { day: 69, month: 3, title: 'O Cuidado com os Pobres, Viúvas e Estrangeiros', read: 'Deuteronômio 13-15 • São Lucas 10', bookId: 'dt', chapter: 13 },
  { day: 70, month: 3, title: 'O Bom Samaritano e Maria aos Pés de Jesus', read: 'Deuteronômio 16-18 • São Lucas 11', bookId: 'lc', chapter: 10 },
  { day: 71, month: 3, title: 'A Promessa do Grande Profeta e as Testemunhas', read: 'Deuteronômio 19-21 • São Lucas 12', bookId: 'dt', chapter: 19 },
  { day: 72, month: 3, title: 'A Justiça Social e os Primeiros Frutos da Terra', read: 'Deuteronômio 22-24 • São Lucas 13', bookId: 'dt', chapter: 22 },
  { day: 73, month: 3, title: 'As Bênçãos no Monte Garizim e a Opção pela Vida', read: 'Deuteronômio 25-27 • São Lucas 14', bookId: 'dt', chapter: 25 },
  { day: 74, month: 3, title: 'O Filho Pródigo e o Pai das Misericórdias', read: 'Deuteronômio 28-30 • São Lucas 15', bookId: 'lc', chapter: 15 },
  { day: 75, month: 3, title: 'O Cântico de Moisés e a Bênção Final', read: 'Deuteronômio 31-34 • São Lucas 16', bookId: 'dt', chapter: 31 },
  { day: 76, month: 3, title: 'Os Dez Leprosos e a Oração Incessante', read: 'Josué 1-3 • São Lucas 17-18', bookId: 'js', chapter: 1 },
  { day: 77, month: 3, title: 'Zaqueu, a Entrada em Jerusalém e o Sermão do Monte', read: 'Josué 4-6 • São Lucas 19-20', bookId: 'lc', chapter: 19 },
  { day: 78, month: 3, title: 'A Última Ceia, a Agonia e o Caminho do Calvário', read: 'Josué 7-9 • São Lucas 21-22', bookId: 'lc', chapter: 21 },
  { day: 79, month: 3, title: 'A Cruz, a Redenção e os Discípulos de Emaús', read: 'Josué 10-12 • São Lucas 23-24', bookId: 'lc', chapter: 23 },
  { day: 80, month: 3, title: 'A Conquista de Canaã e a Divisão das Terras', read: 'Josué 13-15 • Salmos 39', bookId: 'js', chapter: 13 },
  { day: 81, month: 3, title: 'A Partilha com as Tribos e a Casa de Deus em Silo', read: 'Josué 16-18 • Salmos 40', bookId: 'js', chapter: 16 },
  { day: 82, month: 3, title: 'As Cidades Levíticas e a Paz em Israel', read: 'Josué 19-21 • Salmos 41', bookId: 'js', chapter: 19 },
  { day: 83, month: 3, title: 'Eu e Minha Casa Serviremos ao Senhor: A Aliança em Siquém', read: 'Josué 22-24 • Salmos 42', bookId: 'js', chapter: 22 },
  { day: 84, month: 3, title: 'Os Primeiros Juízes: Otoniel, Eúde e Débora', read: 'Juízes 1-3 • Salmos 43', bookId: 'jz', chapter: 1 },
  { day: 85, month: 3, title: 'O Cântico de Débora e o Chamado de Gideão', read: 'Juízes 4-6 • Salmos 44', bookId: 'jz', chapter: 4 },
  { day: 86, month: 3, title: 'Os Trezentos de Gideão e a Queda de Madiã', read: 'Juízes 7-9 • Salmos 45', bookId: 'jz', chapter: 7 },
  { day: 87, month: 3, title: 'Jefté, Sansão e a Força do Espírito Santo', read: 'Juízes 10-13 • Salmos 47', bookId: 'jz', chapter: 10 },
  { day: 88, month: 3, title: 'As Façanhas e a Queda de Sansão', read: 'Juízes 14-16 • Salmos 48', bookId: 'jz', chapter: 14 },
  { day: 89, month: 3, title: 'A Tribo de Dã e as Tribulações em Israel', read: 'Juízes 17-21 • Salmos 49', bookId: 'jz', chapter: 17 },
  { day: 90, month: 3, title: 'Rute, a Moabita Fiel, e Boaz: A Linhagem Real', read: 'Rute 1-4 • Salmos 50', bookId: 'rt', chapter: 1 },

  // ==========================================
  // MÊS 4 (ABRIL): DIAS 91 A 120
  // 1 Samuel (1-31) & São João (1-21)
  // ==========================================
  { day: 91, month: 4, title: 'No Princípio Era o Verbo e a Vocação de Samuel', read: '1 Samuel 1-3 • São João 1', bookId: 'joa', chapter: 1 },
  { day: 92, month: 4, title: 'As Bodas de Caná e a Arca entre os Filisteus', read: '1 Samuel 4-6 • São João 2', bookId: 'joa', chapter: 2 },
  { day: 93, month: 4, title: 'Nicodemos e o Renascer da Água e do Espírito', read: '1 Samuel 7-9 • São João 3', bookId: 'joa', chapter: 3 },
  { day: 94, month: 4, title: 'A Samaritana e a Água Viva que Dá a Vida Eterna', read: '1 Samuel 10-12 • São João 4', bookId: 'joa', chapter: 4 },
  { day: 95, month: 4, title: 'A Cura na Piscina de Betesda e o Testemunho do Pai', read: '1 Samuel 13-15 • São João 5', bookId: 'joa', chapter: 5 },
  { day: 96, month: 4, title: 'O Pão da Vida que Desceu dos Céus', read: '1 Samuel 16-17 • São João 6', bookId: 'joa', chapter: 6 },
  { day: 97, month: 4, title: 'Davi Unge e Vence Golias pela Fé no Deus Vivo', read: '1 Samuel 18-20 • São João 7', bookId: '1sm', chapter: 17 },
  { day: 98, month: 4, title: 'A Mulher Adúltera e Eu Sou a Luz do Mundo', read: '1 Samuel 21-23 • São João 8', bookId: 'joa', chapter: 8 },
  { day: 99, month: 4, title: 'A Cura do Cego de Nascença', read: '1 Samuel 24-26 • São João 9', bookId: 'joa', chapter: 9 },
  { day: 100, month: 4, title: 'O Bom Pastor que Dá a Vida pelas Suas Ovelhas', read: '1 Samuel 27-29 • São João 10', bookId: 'joa', chapter: 10 },
  { day: 101, month: 4, title: 'A Morte de Saul e a Ressurreição de Lázaro', read: '1 Samuel 30-31 • São João 11', bookId: 'joa', chapter: 11 },
  { day: 102, month: 4, title: 'A Unção em Betânia e o Grão de Trigo que Morre para Dar Fruto', read: '2 Samuel 1-3 • São João 12', bookId: 'joa', chapter: 12 },
  { day: 103, month: 4, title: 'O Lava-Pés e o Mandamento Novo do Amor Fraterno', read: '2 Samuel 4-6 • São João 13', bookId: 'joa', chapter: 13 },
  { day: 104, month: 4, title: 'Eu Sou o Caminho, a Verdade e a Vida', read: '2 Samuel 7-9 • São João 14', bookId: 'joa', chapter: 14 },
  { day: 105, month: 4, title: 'A Videira Verdadeira e a Alegria Completa', read: '2 Samuel 10-12 • São João 15', bookId: 'joa', chapter: 15 },
  { day: 106, month: 4, title: 'O Consolador Santo Espírito e a Vitória sobre o Mundo', read: '2 Samuel 13-15 • São João 16', bookId: 'joa', chapter: 16 },
  { day: 107, month: 4, title: 'A Oração Sacerdotal de Jesus pela Unidade', read: '2 Samuel 16-18 • São João 17', bookId: 'joa', chapter: 17 },
  { day: 108, month: 4, title: 'A Prisão, o Interrogatório e o Julgamento de Jesus', read: '2 Samuel 19-21 • São João 18', bookId: 'joa', chapter: 18 },
  { day: 109, month: 4, title: 'Ecce Homo, a Morte na Cruz e Maria aos Pés do Calvário', read: '2 Samuel 22-24 • São João 19', bookId: 'joa', chapter: 19 },
  { day: 110, month: 4, title: 'O Sepulcro Vazio, Maria Madalena e São Tomé', read: 'Salmos 51-53 • São João 20', bookId: 'joa', chapter: 20 },
  { day: 111, month: 4, title: 'A Pesca Milagrosa e Pedro, Tu Me Amas?', read: 'Salmos 54-56 • São João 21', bookId: 'joa', chapter: 21 },
  { day: 112, month: 4, title: 'A Sabedoria de Salomão e o Início da Monarquia', read: '1 Reis 1-3 • Salmos 57', bookId: '1rs', chapter: 1 },
  { day: 113, month: 4, title: 'O Julgamento Sábio e a Riqueza de Salomão', read: '1 Reis 4-6 • Salmos 58', bookId: '1rs', chapter: 4 },
  { day: 114, month: 4, title: 'A Dedicação do Templo em Jerusalém', read: '1 Reis 7-8 • Salmos 59', bookId: '1rs', chapter: 7 },
  { day: 115, month: 4, title: 'A Rainha de Sabá e a Glória de Salomão', read: '1 Reis 9-11 • Salmos 60', bookId: '1rs', chapter: 9 },
  { day: 116, month: 4, title: 'A Divisão dos Reinos: Judá e Israel', read: '1 Reis 12-14 • Salmos 61', bookId: '1rs', chapter: 12 },
  { day: 117, month: 4, title: 'Elias, o Profeta de Fogo, e a Viúva de Sarepta', read: '1 Reis 15-17 • Salmos 63', bookId: '1rs', chapter: 15 },
  { day: 118, month: 4, title: 'O Desafio no Monte Carmelo e a Brisa Suave no Horeb', read: '1 Reis 18-19 • Salmos 64', bookId: '1rs', chapter: 18 },
  { day: 119, month: 4, title: 'A Vinha de Nabot e a Vocação de Eliseu', read: '1 Reis 20-22 • Salmos 65', bookId: '1rs', chapter: 20 },
  { day: 120, month: 4, title: 'O Carro de Fogo e a Capa de Elias', read: '2 Reis 1-3 • Salmos 66', bookId: '2rs', chapter: 1 },

  // ==========================================
  // MÊS 5 (MAIO): DIAS 121 A 151
  // 2 Reis (4-25) & Atos dos Apóstolos (1-28)
  // ==========================================
  { day: 121, month: 5, title: 'A Ascensão de Jesus e a Escolha de Matias', read: '2 Reis 4-5 • Atos 1', bookId: 'at', chapter: 1 },
  { day: 122, month: 5, title: 'Pentecostes: O Batismo no Espírito Santo', read: '2 Reis 6-7 • Atos 2', bookId: 'at', chapter: 2 },
  { day: 123, month: 5, title: 'A Cura do Paralítico na Porta Formosa', read: '2 Reis 8-9 • Atos 3', bookId: 'at', chapter: 3 },
  { day: 124, month: 5, title: 'A Ousadia dos Apóstolos perante o Sinédrio', read: '2 Reis 10-11 • Atos 4', bookId: 'at', chapter: 4 },
  { day: 125, month: 5, title: 'Os Milagres dos Apóstolos e o Conselho de Gamaliel', read: '2 Reis 12-13 • Atos 5', bookId: 'at', chapter: 5 },
  { day: 126, month: 5, title: 'A Instituição dos Diáconos e a Sabedoria de Estêvão', read: '2 Reis 14-15 • Atos 6', bookId: 'at', chapter: 6 },
  { day: 127, month: 5, title: 'O Martírio de São Estêvão, Primeiro Mártir', read: '2 Reis 16-17 • Atos 7', bookId: 'at', chapter: 7 },
  { day: 128, month: 5, title: 'Filipe em Samaria e o Batismo do Etíope', read: '2 Reis 18-19 • Atos 8', bookId: 'at', chapter: 8 },
  { day: 129, month: 5, title: 'A Conversão de Saulo na Estrada de Damasco', read: '2 Reis 20-21 • Atos 9', bookId: 'at', chapter: 9 },
  { day: 130, month: 5, title: 'Cornélio e a Abertura do Evangelho a Todos os Povos', read: '2 Reis 22-23 • Atos 10', bookId: 'at', chapter: 10 },
  { day: 131, month: 5, title: 'A Igreja em Antioquia e a Libertação Milagrosa de Pedro', read: '2 Reis 24-25 • Atos 11-12', bookId: 'at', chapter: 11 },
  { day: 132, month: 5, title: 'A Primeira Viagem Missionária de Paulo e Barnabé', read: '1 Crônicas 1-3 • Atos 13', bookId: '1cr', chapter: 1 },
  { day: 133, month: 5, title: 'A Pregação em Listra e Derbe e o Retorno a Antioquia', read: '1 Crônicas 4-6 • Atos 14', bookId: 'at', chapter: 14 },
  { day: 134, month: 5, title: 'O Concílio de Jerusalém: Salvação Pela Graça de Cristo', read: '1 Crônicas 7-9 • Atos 15', bookId: 'at', chapter: 15 },
  { day: 135, month: 5, title: 'Paulo e Silas na Prisão de Filipos e o Hino da Meia-Noite', read: '1 Crônicas 10-12 • Atos 16', bookId: 'at', chapter: 16 },
  { day: 136, month: 5, title: 'O Discurso no Areópago de Atenas ao Deus Desconhecido', read: '1 Crônicas 13-15 • Atos 17', bookId: 'at', chapter: 17 },
  { day: 137, month: 5, title: 'Paulo em Corinto e a Chegada a Éfeso', read: '1 Crônicas 16-18 • Atos 18', bookId: 'at', chapter: 18 },
  { day: 138, month: 5, title: 'Os Milagres em Éfeso e a Vitória sobre a Idolatria', read: '1 Crônicas 19-21 • Atos 19', bookId: 'at', chapter: 19 },
  { day: 139, month: 5, title: 'A Despedida comovente dos Anciãos de Éfeso em Mileto', read: '1 Crônicas 22-24 • Atos 20', bookId: 'at', chapter: 20 },
  { day: 140, month: 5, title: 'Paulo Chega a Jerusalém e é Preso no Templo', read: '1 Crônicas 25-27 • Atos 21', bookId: 'at', chapter: 21 },
  { day: 141, month: 5, title: 'O Testemunho de Paulo perante o Povo e o Sinédrio', read: '1 Crônicas 28-29 • Atos 22-23', bookId: 'at', chapter: 22 },
  { day: 142, month: 5, title: 'Paulo Defende a Fé diante dos Governadores Félix e Festo', read: '2 Crônicas 1-3 • Atos 24-25', bookId: '2cr', chapter: 1 },
  { day: 143, month: 5, title: 'A Apologia de Paulo perante o Rei Agripa', read: '2 Crônicas 4-6 • Atos 26', bookId: 'at', chapter: 26 },
  { day: 144, month: 5, title: 'A Tempestade, o Naufrágio e a Ilha de Malta', read: '2 Crônicas 7-9 • Atos 27', bookId: 'at', chapter: 27 },
  { day: 145, month: 5, title: 'Paulo em Roma Proclamando o Reino de Deus com Liberdade', read: '2 Crônicas 10-12 • Atos 28', bookId: 'at', chapter: 28 },
  { day: 146, month: 5, title: 'A Fé dos Reis de Judá: Asafe e Josafá', read: '2 Crônicas 13-16 • Salmos 67', bookId: '2cr', chapter: 13 },
  { day: 147, month: 5, title: 'A Grande Vitória de Josafá através do Louvor', read: '2 Crônicas 17-20 • Salmos 68', bookId: '2cr', chapter: 17 },
  { day: 148, month: 5, title: 'Joás e a Restauração da Casa de Deus', read: '2 Crônicas 21-24 • Salmos 69', bookId: '2cr', chapter: 21 },
  { day: 149, month: 5, title: 'Ozias, Jotão e o Reinado de Acaz', read: '2 Crônicas 25-28 • Salmos 70', bookId: '2cr', chapter: 25 },
  { day: 150, month: 5, title: 'Ezequias Celebra a Páscoa e Renova a Fé', read: '2 Crônicas 29-32 • Salmos 71', bookId: '2cr', chapter: 29 },
  { day: 151, month: 5, title: 'Josias e a Descoberta do Livro da Lei Sagrada', read: '2 Crônicas 33-36 • Salmos 72', bookId: '2cr', chapter: 33 },

  // ==========================================
  // MÊS 6 (JUNHO): DIAS 152 A 181
  // Esdras, Neemias, Tobias, Judite, Ester & Romanos (1-16), 1 Coríntios (1-16)
  // ==========================================
  { day: 152, month: 6, title: 'O Decreto de Ciro e o Retorno do Cativeiro', read: 'Esdras 1-3 • Romanos 1', bookId: 'esd', chapter: 1 },
  { day: 153, month: 6, title: 'A Reconstrução do Altar e o Templo Reerguido', read: 'Esdras 4-7 • Romanos 2-3', bookId: 'esd', chapter: 4 },
  { day: 154, month: 6, title: 'A Oração Penitencial de Esdras e a Reforma Espiritual', read: 'Esdras 8-10 • Romanos 4-5', bookId: 'esd', chapter: 8 },
  { day: 155, month: 6, title: 'Neemias Chora por Jerusalém e Reergue os Muros', read: 'Neemias 1-3 • Romanos 6-7', bookId: 'ne', chapter: 1 },
  { day: 156, month: 6, title: 'Vida no Espírito e Nenhuma Condenação em Cristo', read: 'Neemias 4-7 • Romanos 8', bookId: 'rm', chapter: 8 },
  { day: 157, month: 6, title: 'A Leitura Pública da Lei e o Avivamento Espiritual', read: 'Neemias 8-10 • Romanos 9-10', bookId: 'ne', chapter: 8 },
  { day: 158, month: 6, title: 'A Dedicação dos Muros e a Misericórdia Divina', read: 'Neemias 11-13 • Romanos 11-12', bookId: 'ne', chapter: 11 },
  { day: 159, month: 6, title: 'O Amor ao Próximo e a Fraternidade Cristã', read: 'Tobias 1-4 • Romanos 13-14', bookId: 'tb', chapter: 1 },
  { day: 160, month: 6, title: 'O Anjo São Rafael Guia o Jovem Tobias com Paz', read: 'Tobias 5-8 • Romanos 15-16', bookId: 'tb', chapter: 5 },
  { day: 161, month: 6, title: 'A Cura dos Olhos de Tobit e o Cântico de Ação de Graças', read: 'Tobias 9-14 • 1 Coríntios 1', bookId: 'tb', chapter: 9 },
  { day: 162, month: 6, title: 'A Coragem e a Fé de Judite em Favor do Povo', read: 'Judite 1-4 • 1 Coríntios 2-3', bookId: 'jdt', chapter: 1 },
  { day: 163, month: 6, title: 'A Oração de Judite e a Confiança no Deus dos Humildes', read: 'Judite 5-8 • 1 Coríntios 4-5', bookId: 'jdt', chapter: 5 },
  { day: 164, month: 6, title: 'A Libertação de Betúlia e o Cântico Triunfal', read: 'Judite 9-12 • 1 Coríntios 6-7', bookId: 'jdt', chapter: 9 },
  { day: 165, month: 6, title: 'A Vitória de Judite e a Paz em Israel', read: 'Judite 13-16 • 1 Coríntios 8-9', bookId: 'jdt', chapter: 13 },
  { day: 166, month: 6, title: 'A Rainha Ester e o Jejum pela Salvação do Povo', read: 'Ester 1-3 • 1 Coríntios 10', bookId: 'est', chapter: 1 },
  { day: 167, month: 6, title: 'A Coragem de Ester diante do Rei e a Queda de Amã', read: 'Ester 4-7 • 1 Coríntios 11', bookId: 'est', chapter: 4 },
  { day: 168, month: 6, title: 'O Triunfo dos Judeus e a Festa dos Purim', read: 'Ester 8-10 • 1 Coríntios 12', bookId: 'est', chapter: 8 },
  { day: 169, month: 6, title: 'O Hino ao Amor: O Amor Jamais Acabará', read: 'Salmos 73-74 • 1 Coríntios 13', bookId: '1cor', chapter: 13 },
  { day: 170, month: 6, title: 'Os Dons Espirituais e a Profecia que Edifica a Igreja', read: 'Salmos 75-76 • 1 Coríntios 14', bookId: '1cor', chapter: 14 },
  { day: 171, month: 6, title: 'O Grande Hino da Ressurreição de Cristo', read: 'Salmos 77-78 • 1 Coríntios 15', bookId: '1cor', chapter: 15 },
  { day: 172, month: 6, title: 'A Comunhão na Caridade e a Bênção Final', read: 'Salmos 79-80 • 1 Coríntios 16', bookId: '1cor', chapter: 16 },
  { day: 173, month: 6, title: 'O Início da Revolta dos Macabeus em Defesa da Lei', read: '1 Macabeus 1-3 • 2 Coríntios 1', bookId: '1mc', chapter: 1 },
  { day: 174, month: 6, title: 'Judas Macabeu Purifica o Templo Sagrado', read: '1 Macabeus 4-6 • 2 Coríntios 2-3', bookId: '1mc', chapter: 4 },
  { day: 175, month: 6, title: 'O Ministério da Nova Aliança Escrito nos Corações', read: '1 Macabeus 7-9 • 2 Coríntios 4-5', bookId: '2cor', chapter: 4 },
  { day: 176, month: 6, title: 'A Aliança com Roma e as Batalhas de Jônatas', read: '1 Macabeus 10-12 • 2 Coríntios 6-7', bookId: '1mc', chapter: 10 },
  { day: 177, month: 6, title: 'A Generosidade Alegre e a Coleta para os Santos', read: '1 Macabeus 13-16 • 2 Coríntios 8-9', bookId: '2cor', chapter: 8 },
  { day: 178, month: 6, title: 'O Martírio de Eleazar e dos Sete Irmãos Macabeus', read: '2 Macabeus 1-4 • 2 Coríntios 10-11', bookId: '2mc', chapter: 1 },
  { day: 179, month: 6, title: 'A Minha Graça Te Basta: A Força na Fraqueza', read: '2 Macabeus 5-8 • 2 Coríntios 12-13', bookId: '2cor', chapter: 12 },
  { day: 180, month: 6, title: 'A Oração pelos Falecidos e a Fé na Ressurreição', read: '2 Macabeus 9-12 • Gálatas 1-2', bookId: '2mc', chapter: 9 },
  { day: 181, month: 6, title: 'A Visão do Profeta Jeremias e a Vitória Final', read: '2 Macabeus 13-15 • Gálatas 3-4', bookId: '2mc', chapter: 13 },

  // ==========================================
  // MÊS 7 (JULHO): DIAS 182 A 212
  // Jó (1-42), Gálatas (5-6), Efésios (1-6), Filipenses (1-4), Colossenses (1-4)
  // ==========================================
  { day: 182, month: 7, title: 'A Provação de Jó e a Fé que Não Desiste', read: 'Jó 1-3 • Gálatas 5-6', bookId: 'jo', chapter: 1 },
  { day: 183, month: 7, title: 'A Armadura Espiritual e a Bênção em Cristo', read: 'Jó 4-6 • Efésios 1-2', bookId: 'ef', chapter: 1 },
  { day: 184, month: 7, title: 'O Mistério de Cristo e o Amor que Excede Todo Entendimento', read: 'Jó 7-9 • Efésios 3-4', bookId: 'ef', chapter: 3 },
  { day: 185, month: 7, title: 'Andai no Amor e Revesti-vos de Toda a Armadura de Deus', read: 'Jó 10-12 • Efésios 5-6', bookId: 'ef', chapter: 5 },
  { day: 186, month: 7, title: 'Alegrai-vos Sempre no Senhor e a Humildade de Cristo', read: 'Jó 13-15 • Filipenses 1-2', bookId: 'flp', chapter: 1 },
  { day: 187, month: 7, title: 'Tudo Posso Naquele que Me Fortalece', read: 'Jó 16-18 • Filipenses 3-4', bookId: 'flp', chapter: 3 },
  { day: 188, month: 7, title: 'A Supremacia de Cristo sobre Toda a Criação', read: 'Jó 19-21 • Colossenses 1-2', bookId: 'col', chapter: 1 },
  { day: 189, month: 7, title: 'Pensai nas Coisas do Alto e Revesti-vos de Misericórdia', read: 'Jó 22-24 • Colossenses 3-4', bookId: 'col', chapter: 3 },
  { day: 190, month: 7, title: 'A Esperança e a Vigilância na Vinda do Senhor', read: 'Jó 25-27 • 1 Tessalonicenses 1-3', bookId: '1ts', chapter: 1 },
  { day: 191, month: 7, title: 'A Santificação e a Oração Incessante', read: 'Jó 28-30 • 1 Tessalonicenses 4-5', bookId: '1ts', chapter: 4 },
  { day: 192, month: 7, title: 'A Perseverança na Fé e o Amor a Todos', read: 'Jó 31-33 • 2 Tessalonicenses 1-3', bookId: '2ts', chapter: 1 },
  { day: 193, month: 7, title: 'A Oração por Todos os Homens e a Boa Doutrina', read: 'Jó 34-36 • 1 Timóteo 1-3', bookId: '1tm', chapter: 1 },
  { day: 194, month: 7, title: 'O Bom Combate da Fé e o Cuidado com os Irmãos', read: 'Jó 37-39 • 1 Timóteo 4-6', bookId: '1tm', chapter: 4 },
  { day: 195, month: 7, title: 'Deus Revela a Sua Onipotência e Jó Encontra a Paz', read: 'Jó 40-42 • 2 Timóteo 1-2', bookId: 'jo', chapter: 40 },
  { day: 196, month: 7, title: 'Combati o Bom Combate, Guardei a Fé', read: 'Salmos 81-83 • 2 Timóteo 3-4', bookId: '2tm', chapter: 3 },
  { day: 197, month: 7, title: 'A Graça que Salva a Todos e a Fraternidade em Cristo', read: 'Salmos 84-86 • Tito 1-3 • Filemon', bookId: 'tit', chapter: 1 },
  { day: 198, month: 7, title: 'Jesus, Sacerdote Eterno Superior aos Anjos', read: 'Salmos 87-89 • Hebreus 1-3', bookId: 'heb', chapter: 1 },
  { day: 199, month: 7, title: 'A Palavra Viva e Eficaz e o Trono da Graça', read: 'Salmos 90-92 • Hebreus 4-6', bookId: 'heb', chapter: 4 },
  { day: 200, month: 7, title: 'Jesus, Mediador da Nova e Eterna Aliança', read: 'Salmos 93-95 • Hebreus 7-9', bookId: 'heb', chapter: 7 },
  { day: 201, month: 7, title: 'A Nuvem de Testemunhas e a Galeria dos Heróis da Fé', read: 'Salmos 96-98 • Hebreus 10-11', bookId: 'heb', chapter: 10 },
  { day: 202, month: 7, title: 'Olhando Firme para Jesus, Autor e Consumador da Fé', read: 'Salmos 99-101 • Hebreus 12-13', bookId: 'heb', chapter: 12 },
  { day: 203, month: 7, title: 'A Fé sem Obras é Morta: A Prática da Caridade', read: 'Salmos 102-103 • Tiago 1-3', bookId: 'tg', chapter: 1 },
  { day: 204, month: 7, title: 'A Sabedoria que Vem do Alto e a Oração dos Enfermos', read: 'Salmos 104-105 • Tiago 4-5', bookId: 'tg', chapter: 4 },
  { day: 205, month: 7, title: 'Povo Escolhido, Sacerdócio Real e Nação Santa', read: 'Salmos 106-107 • 1 Pedro 1-3', bookId: '1pe', chapter: 1 },
  { day: 206, month: 7, title: 'Lançai sobre Ele Toda Ansiedade, Pois Ele Cuida de Vós', read: 'Salmos 108-110 • 1 Pedro 4-5', bookId: '1pe', chapter: 4 },
  { day: 207, month: 7, title: 'As Preciosas Promessas e a Esperança dos Novos Céus', read: 'Salmos 111-114 • 2 Pedro 1-3', bookId: '2pe', chapter: 1 },
  { day: 208, month: 7, title: 'Andar na Luz e o Amor que Vem de Deus', read: 'Salmos 115-117 • 1 João 1-3', bookId: '1jo', chapter: 1 },
  { day: 209, month: 7, title: 'Deus é Amor e Quem Ama Permanece em Deus', read: 'Salmos 118 • 1 João 4-5', bookId: '1jo', chapter: 4 },
  { day: 210, month: 7, title: 'A Verdade no Amor e a Fidelidade Apostólica', read: 'Salmos 119, 1-48 • 2 João • 3 João • Judas', bookId: 'jud', chapter: 1 },
  { day: 211, month: 7, title: 'A Revelação de Jesus Cristo e as Sete Igrejas', read: 'Salmos 119, 49-96 • Apocalipse 1-3', bookId: 'ap', chapter: 1 },
  { day: 212, month: 7, title: 'O Cordeiro Digno de Abrir o Livro Selado', read: 'Salmos 119, 97-176 • Apocalipse 4-6', bookId: 'ap', chapter: 4 },

  // ==========================================
  // MÊS 8 (AGOSTO): DIAS 213 A 243
  // Salmos (120-150), Provérbios (1-31) & Apocalipse (7-22)
  // ==========================================
  { day: 213, month: 8, title: 'A Grande Multidão de Todas as Nações diante do Trono', read: 'Salmos 120-123 • Apocalipse 7-9', bookId: 'ap', chapter: 7 },
  { day: 214, month: 8, title: 'O Livro Doce como Mel e as Duas Testemunhas', read: 'Salmos 124-127 • Apocalipse 10-12', bookId: 'ap', chapter: 10 },
  { day: 215, month: 8, title: 'A Mulher Vestida de Sol e a Vitória do Cordeiro', read: 'Salmos 128-131 • Apocalipse 13-15', bookId: 'ap', chapter: 13 },
  { day: 216, month: 8, title: 'O Cântico de Moisés e do Cordeiro', read: 'Salmos 132-135 • Apocalipse 16-18', bookId: 'ap', chapter: 16 },
  { day: 217, month: 8, title: 'As Bodas do Cordeiro e o Cavaleiro Fiel e Verdadeiro', read: 'Salmos 136-138 • Apocalipse 19-20', bookId: 'ap', chapter: 19 },
  { day: 218, month: 8, title: 'A Nova Jerusalém: Novos Céus e Nova Terra', read: 'Salmos 139-141 • Apocalipse 21-22', bookId: 'ap', chapter: 21 },
  { day: 219, month: 8, title: 'Louvai ao Senhor no Seu Santuário! Tudo o que Respira Louve o Senhor', read: 'Salmos 142-150', bookId: 'sl', chapter: 142 },
  { day: 220, month: 8, title: 'O Princípio da Sabedoria é o Temor do Senhor', read: 'Provérbios 4-6', bookId: 'pv', chapter: 4 },
  { day: 221, month: 8, title: 'A Sabedoria Edifica a Sua Casa', read: 'Provérbios 7-9', bookId: 'pv', chapter: 7 },
  { day: 222, month: 8, title: 'A Língua dos Sábios e o Tesouro da Prudência', read: 'Provérbios 10-12', bookId: 'pv', chapter: 10 },
  { day: 223, month: 8, title: 'A Resposta Branda Desvia o Furor', read: 'Provérbios 13-15', bookId: 'pv', chapter: 13 },
  { day: 224, month: 8, title: 'O Coração do Homem Planeja, mas a Resposta Vem do Senhor', read: 'Provérbios 16-18', bookId: 'pv', chapter: 16 },
  { day: 225, month: 8, title: 'A Generosidade com os Pobres Empresta a Deus', read: 'Provérbios 19-21', bookId: 'pv', chapter: 19 },
  { day: 226, month: 8, title: 'O Bom Nome Vale Mais do que Muitas Riquezas', read: 'Provérbios 22-24', bookId: 'pv', chapter: 22 },
  { day: 227, month: 8, title: 'A Palavra Dita no Tempo Certo é Maçã de Ouro', read: 'Provérbios 25-27', bookId: 'pv', chapter: 25 },
  { day: 228, month: 8, title: 'A Confiança dos Justos e o Elogio da Mulher Virtuosa', read: 'Provérbios 28-31', bookId: 'pv', chapter: 28 },
  { day: 229, month: 8, title: 'Tudo Tem o Seu Tempo Determinado por Deus', read: 'Eclesiastes 1-4', bookId: 'ec', chapter: 1 },
  { day: 230, month: 8, title: 'Melhor São Dois do que Um: A Sabedoria da Humildade', read: 'Eclesiastes 5-8', bookId: 'ec', chapter: 5 },
  { day: 231, month: 8, title: 'Lembra-te do Teu Criador nos Dias da Tua Juventude', read: 'Eclesiastes 9-12', bookId: 'ec', chapter: 9 },
  { day: 232, month: 8, title: 'O Amor é Forte como a Morte: Cântico dos Cânticos', read: 'Cântico dos Cânticos 1-4', bookId: 'ct', chapter: 1 },
  { day: 233, month: 8, title: 'O Meu Amado é Meu, e Eu Sou Dele', read: 'Cântico dos Cânticos 5-8', bookId: 'ct', chapter: 5 },
  { day: 234, month: 8, title: 'A Busca da Sabedoria e a Imortalidade da Alma', read: 'Sabedoria 1-3', bookId: 'sb', chapter: 1 },
  { day: 235, month: 8, title: 'A Sabedoria é o Reflexo da Luz Eterna de Deus', read: 'Sabedoria 4-6', bookId: 'sb', chapter: 4 },
  { day: 236, month: 8, title: 'A Oração de Salomão para Receber a Santa Sabedoria', read: 'Sabedoria 7-9', bookId: 'sb', chapter: 7 },
  { day: 237, month: 8, title: 'A Sabedoria Guiou os Patriarcas no Deserto', read: 'Sabedoria 10-12', bookId: 'sb', chapter: 10 },
  { day: 238, month: 8, title: 'A Providência Divina e a Advertência contra a Idolatria', read: 'Sabedoria 13-15', bookId: 'sb', chapter: 13 },
  { day: 239, month: 8, title: 'A Criação Harmoniosa e o Louvor ao Deus Libertador', read: 'Sabedoria 16-19', bookId: 'sb', chapter: 16 },
  { day: 240, month: 8, title: 'O Temor de Deus é a Raiz de Toda a Sabedoria', read: 'Eclesiástico 1-3', bookId: 'ecli', chapter: 1 },
  { day: 241, month: 8, title: 'A Fidelidade na Provação e o Perdão das Ofensas', read: 'Eclesiástico 4-6', bookId: 'ecli', chapter: 4 },
  { day: 242, month: 8, title: 'A Amizade Verdadeira e a Sabedoria na Convivência', read: 'Eclesiástico 7-9', bookId: 'ecli', chapter: 7 },
  { day: 243, month: 8, title: 'A Humildade, o Controle da Língua e a Generosidade', read: 'Eclesiástico 10-12', bookId: 'ecli', chapter: 10 },

  // ==========================================
  // MÊS 9 (SETEMBRO): DIAS 244 A 273
  // Eclesiástico (13-51) & Isaías (1-39)
  // ==========================================
  { day: 244, month: 9, title: 'A Verdadeira Sabedoria e a Riqueza que Vem de Deus', read: 'Eclesiástico 13-16', bookId: 'ecli', chapter: 13 },
  { day: 245, month: 9, title: 'O Livre-Arbítrio e a Misericórdia Divina sem Fim', read: 'Eclesiástico 17-20', bookId: 'ecli', chapter: 17 },
  { day: 246, month: 9, title: 'A Prudência nas Palavras e o Valor da Paciência', read: 'Eclesiástico 21-24', bookId: 'ecli', chapter: 21 },
  { day: 247, month: 9, title: 'A Família Santa, o Respeito aos Pais e a Fraternidade', read: 'Eclesiástico 25-28', bookId: 'ecli', chapter: 25 },
  { day: 248, month: 9, title: 'A Bênção do Trabalho Digno e a Paz de Consciência', read: 'Eclesiástico 29-32', bookId: 'ecli', chapter: 29 },
  { day: 249, month: 9, title: 'A Oração por Toda a Humanidade e o Louvor a Deus', read: 'Eclesiástico 33-36', bookId: 'ecli', chapter: 33 },
  { day: 250, month: 9, title: 'A Saúde, os Médicos e o Equilíbrio Espiritual', read: 'Eclesiástico 37-40', bookId: 'ecli', chapter: 37 },
  { day: 251, month: 9, title: 'As Maravilhas da Criação: Sol, Lua, Estrelas e o Mar', read: 'Eclesiástico 41-44', bookId: 'ecli', chapter: 41 },
  { day: 252, month: 9, title: 'O Elogio aos Santos Patriarcas, Profetas e Sacerdotes', read: 'Eclesiástico 45-48', bookId: 'ecli', chapter: 45 },
  { day: 253, month: 9, title: 'O Grande Sacerdote Simão e a Oração Final de Ação de Graças', read: 'Eclesiástico 49-51', bookId: 'ecli', chapter: 49 },
  { day: 254, month: 9, title: 'Vinde e Debatamos: Embora Vossos Pecados Sejam Escarlates', read: 'Isaías 1-3', bookId: 'is', chapter: 1 },
  { day: 255, month: 9, title: 'O Monte da Casa do Senhor e o Cântico da Vinha Amada', read: 'Isaías 4-6', bookId: 'is', chapter: 4 },
  { day: 256, month: 9, title: 'Eis que a Virgem Conceberá e Dará à Luz Emanuel (Deus Conosco)', read: 'Isaías 7-9', bookId: 'is', chapter: 7 },
  { day: 257, month: 9, title: 'O Rebento de Jessé e o Espírito de Sabedoria e Fortaleza', read: 'Isaías 10-12', bookId: 'is', chapter: 10 },
  { day: 258, month: 9, title: 'O Cântico de Ação de Graças e a Profecia sobre as Nações', read: 'Isaías 13-16', bookId: 'is', chapter: 13 },
  { day: 259, month: 9, title: 'O Julgamento das Nações e a Esperança de Paz Universal', read: 'Isaías 17-20', bookId: 'is', chapter: 17 },
  { day: 260, month: 9, title: 'A Sentinela da Noite e a Visão do Vale das Lágrimas', read: 'Isaías 21-24', bookId: 'is', chapter: 21 },
  { day: 261, month: 9, title: 'O Banquete Messiânico e a Destruição da Morte para Sempre', read: 'Isaías 25-27', bookId: 'is', chapter: 25 },
  { day: 262, month: 9, title: 'A Pedra Angular Preciosa em Sião e a Justiça Divina', read: 'Isaías 28-30', bookId: 'is', chapter: 28 },
  { day: 263, month: 9, title: 'A Efusão do Espírito Santo e a Justiça que Produz Paz', read: 'Isaías 31-33', bookId: 'is', chapter: 31 },
  { day: 264, month: 9, title: 'O Deserto Florescerá e o Caminho Sagrado da Redenção', read: 'Isaías 34-36', bookId: 'is', chapter: 34 },
  { day: 265, month: 9, title: 'A Oração de Ezequias, a Cura e o Livramento de Jerusalém', read: 'Isaías 37-39', bookId: 'is', chapter: 37 },
  { day: 266, month: 9, title: 'Consolai, Consolai o Meu Povo: Uma Voz Clama no Deserto', read: 'Isaías 40-42', bookId: 'is', chapter: 40 },
  { day: 267, month: 9, title: 'Não Temas, Pois Eu Te Remi; Chamei-te pelo Teu Nome', read: 'Isaías 43-45', bookId: 'is', chapter: 43 },
  { day: 268, month: 9, title: 'Eu Sou Deus e Não Há Outro: O Deus que Sustenta na Velhice', read: 'Isaías 46-48', bookId: 'is', chapter: 46 },
  { day: 269, month: 9, title: 'Luz para as Nações: Pode uma Mãe Esquecer seu Filho?', read: 'Isaías 49-51', bookId: 'is', chapter: 49 },
  { day: 270, month: 9, title: 'O Servo Sofredor: Ele Foi Ferido pelas Nossas Transgressões', read: 'Isaías 52-54', bookId: 'is', chapter: 52 },
  { day: 271, month: 9, title: 'Vós que Tendes Sede, Vinde às Águas da Graça', read: 'Isaías 55-57', bookId: 'is', chapter: 55 },
  { day: 272, month: 9, title: 'O Jejum que Agrada a Deus: Partir o Pão com o Faminto', read: 'Isaías 58-61', bookId: 'is', chapter: 58 },
  { day: 273, month: 9, title: 'Levanta-te, Resplandece, Sião! Novos Céus e Nova Terra', read: 'Isaías 62-66', bookId: 'is', chapter: 62 },

  // ==========================================
  // MÊS 10 (OUTUBRO): DIAS 274 A 304
  // Jeremias (1-52), Lamentações (1-5), Baruc (1-6)
  // ==========================================
  { day: 274, month: 10, title: 'Antes que Te Formasses no Ventre, Eu Te Conhecia e Te Consagrei', read: 'Jeremias 1-3', bookId: 'jr', chapter: 1 },
  { day: 275, month: 10, title: 'O Apelo à Conversão e a Fonte de Águas Vivas', read: 'Jeremias 4-6', bookId: 'jr', chapter: 4 },
  { day: 276, month: 10, title: 'O Sermão da Porta do Templo e a Verdadeira Obediência', read: 'Jeremias 7-9', bookId: 'jr', chapter: 7 },
  { day: 277, month: 10, title: 'O Deus Criador e a Aliança Eterna', read: 'Jeremias 10-13', bookId: 'jr', chapter: 10 },
  { day: 278, month: 10, title: 'A Oração na Seca e o Homem que Confia no Senhor', read: 'Jeremias 14-17', bookId: 'jr', chapter: 14 },
  { day: 279, month: 10, title: 'O Vaso nas Mãos do Oleiro Divino', read: 'Jeremias 18-20', bookId: 'jr', chapter: 18 },
  { day: 280, month: 10, title: 'Os Reis de Judá e o Renovo Justo de Davi', read: 'Jeremias 21-24', bookId: 'jr', chapter: 21 },
  { day: 281, month: 10, title: 'Os Setenta Anos do Cativeiro e a Carta aos Exilados', read: 'Jeremias 25-28', bookId: 'jr', chapter: 25 },
  { day: 282, month: 10, title: 'Planos de Paz e Esperança: A Promessa da Nova Aliança', read: 'Jeremias 29-31', bookId: 'jr', chapter: 29 },
  { day: 283, month: 10, title: 'A Compra do Campo em Anatot e a Restauração de Israel', read: 'Jeremias 32-34', bookId: 'jr', chapter: 32 },
  { day: 284, month: 10, title: 'A Fidelidade dos Recabitas e o Rolo Queimado', read: 'Jeremias 35-38', bookId: 'jr', chapter: 35 },
  { day: 285, month: 10, title: 'A Queda de Jerusalém e a Proteção de Jeremias', read: 'Jeremias 39-42', bookId: 'jr', chapter: 39 },
  { day: 286, month: 10, title: 'O Exílio no Egito e as Mensagens às Nações', read: 'Jeremias 43-46', bookId: 'jr', chapter: 43 },
  { day: 287, month: 10, title: 'As Profecias sobre Moabe, Amon e Edom', read: 'Jeremias 47-49', bookId: 'jr', chapter: 47 },
  { day: 288, month: 10, title: 'A Queda da Babilônia e a Libertação dos Cativos', read: 'Jeremias 50-52', bookId: 'jr', chapter: 50 },
  { day: 289, month: 10, title: 'As Lamentações sobre Jerusalém e a Esperança que Renova', read: 'Lamentações 1-2', bookId: 'lm', chapter: 1 },
  { day: 290, month: 10, title: 'As Misericórdias do Senhor Renovam-se a Cada Manhã', read: 'Lamentações 3-5', bookId: 'lm', chapter: 3 },
  { day: 291, month: 10, title: 'A Oração Penitencial dos Exilados na Babilônia', read: 'Baruc 1-3', bookId: 'bar', chapter: 1 },
  { day: 292, month: 10, title: 'A Sabedoria Divina e a Carta de Jeremias contra os Ídolos', read: 'Baruc 4-6', bookId: 'bar', chapter: 4 },
  { day: 293, month: 10, title: 'A Visão da Glória de Deus e o Chamado de Ezequiel', read: 'Ezequiel 1-4', bookId: 'ez', chapter: 1 },
  { day: 294, month: 10, title: 'A Sentinela de Israel e o Rolo das Lamentações', read: 'Ezequiel 5-8', bookId: 'ez', chapter: 5 },
  { day: 295, month: 10, title: 'O Sinal na Testa dos Justos e a Glória que Enche o Templo', read: 'Ezequiel 9-12', bookId: 'ez', chapter: 9 },
  { day: 296, month: 10, title: 'A Responsabilidade Pessoal e o Novo Coração de Carne', read: 'Ezequiel 13-16', bookId: 'ez', chapter: 13 },
  { day: 297, month: 10, title: 'Deus Não Quer a Morte do Pecador, mas que Ele se Converta e Viva', read: 'Ezequiel 17-20', bookId: 'ez', chapter: 17 },
  { day: 298, month: 10, title: 'O Fogo Purificador e o Julgamento de Jerusalém', read: 'Ezequiel 21-24', bookId: 'ez', chapter: 21 },
  { day: 299, month: 10, title: 'As Profecias sobre Tiro, Sidom e o Egito', read: 'Ezequiel 25-28', bookId: 'ez', chapter: 25 },
  { day: 300, month: 10, title: 'A Queda do Faraó e a Restauração dos Povos', read: 'Ezequiel 29-32', bookId: 'ez', chapter: 29 },
  { day: 301, month: 10, title: 'O Bom Pastor que Reúne as Ovelhas Perdidas', read: 'Ezequiel 33-36', bookId: 'ez', chapter: 33 },
  { day: 302, month: 10, title: 'A Visão dos Ossos Secos e o Espírito que Ressuscita o Povo', read: 'Ezequiel 37-39', bookId: 'ez', chapter: 37 },
  { day: 303, month: 10, title: 'A Visão do Novo Templo e as Portas Santas', read: 'Ezequiel 40-44', bookId: 'ez', chapter: 40 },
  { day: 304, month: 10, title: 'A Torrente de Água Viva que Brota do Templo e Cura a Terra', read: 'Ezequiel 45-48', bookId: 'ez', chapter: 45 },

  // ==========================================
  // MÊS 11 (NOVEMBRO): DIAS 305 A 334
  // Daniel (1-14) & Os Doze Profetas Menores
  // ==========================================
  { day: 305, month: 11, title: 'Daniel e seus Companheiros na Corte da Babilônia', read: 'Daniel 1-2', bookId: 'dn', chapter: 1 },
  { day: 306, month: 11, title: 'A Fornalha Ardente e o Louvor dos Três Jovens', read: 'Daniel 3-4', bookId: 'dn', chapter: 3 },
  { day: 307, month: 11, title: 'O Banquete de Baltazar e Daniel na Cova dos Leões', read: 'Daniel 5-6', bookId: 'dn', chapter: 5 },
  { day: 308, month: 11, title: 'A Visão do Filho do Homem e as Quatro Feras', read: 'Daniel 7-8', bookId: 'dn', chapter: 7 },
  { day: 309, month: 11, title: 'A Oração de Daniel e as Setenta Semanas Proféticas', read: 'Daniel 9-10', bookId: 'dn', chapter: 9 },
  { day: 310, month: 11, title: 'São Miguel Arcanjo, a Ressurreição e as Estrelas no Firmamento', read: 'Daniel 11-12', bookId: 'dn', chapter: 11 },
  { day: 311, month: 11, title: 'A Castidade de Susana e Daniel contra os Sacerdotes de Bel', read: 'Daniel 13-14', bookId: 'dn', chapter: 13 },
  { day: 312, month: 11, title: 'O Amor Fiel de Deus por Israel: Oseias e Gomer', read: 'Oseias 1-4', bookId: 'os', chapter: 1 },
  { day: 313, month: 11, title: 'Misericórdia Quero, e Não Sacrifícios', read: 'Oseias 5-8', bookId: 'os', chapter: 5 },
  { day: 314, month: 11, title: 'Com Laços de Amor Eu os Atraí: O Amor Paterno de Deus', read: 'Oseias 9-11', bookId: 'os', chapter: 9 },
  { day: 315, month: 11, title: 'Curarei a sua Infidelidade e os Amarei de Todo o Coração', read: 'Oseias 12-14', bookId: 'os', chapter: 12 },
  { day: 316, month: 11, title: 'Rasgai o Vosso Coração e Não as Vossas Vestes', read: 'Joel 1-2', bookId: 'jl', chapter: 1 },
  { day: 317, month: 11, title: 'Derramarei o Meu Espírito sobre Toda a Carne', read: 'Joel 3-4', bookId: 'jl', chapter: 3 },
  { day: 318, month: 11, title: 'O Rugido do Leão em Sião e a Justiça Social', read: 'Amós 1-3', bookId: 'am', chapter: 1 },
  { day: 319, month: 11, title: 'Buscai ao Senhor e Vivei: Corra a Justiça como um Rio', read: 'Amós 4-6', bookId: 'am', chapter: 4 },
  { day: 320, month: 11, title: 'O Prumo do Senhor e a Restauração da Tenda de Davi', read: 'Amós 7-9', bookId: 'am', chapter: 7 },
  { day: 321, month: 11, title: 'O Reino Pertencerá ao Senhor: A Profecia de Abdias', read: 'Abdias 1', bookId: 'ab', chapter: 1 },
  { day: 322, month: 11, title: 'Jonas Foge para Társis e a Oração no Ventre do Grande Peixe', read: 'Jonas 1-2', bookId: 'jn', chapter: 1 },
  { day: 323, month: 11, title: 'A Conversão de Nínive e a Grande Misericórdia de Deus', read: 'Jonas 3-4', bookId: 'jn', chapter: 3 },
  { day: 324, month: 11, title: 'A Denúncia das Injustiças e o Chamado ao Arrependimento', read: 'Miqueias 1-3', bookId: 'mq', chapter: 1 },
  { day: 325, month: 11, title: 'E Tu, Belém de Éfrata: De Ti Sairá o Governador de Israel', read: 'Miqueias 4-5', bookId: 'mq', chapter: 4 },
  { day: 326, month: 11, title: 'Praticar a Justiça, Amar a Misericórdia e Andar Humildemente com Deus', read: 'Miqueias 6-7', bookId: 'mq', chapter: 6 },
  { day: 327, month: 11, title: 'Eis sobre os Montes os Pés do que Anuncia as Boas-Novas de Paz', read: 'Naum 1-3', bookId: 'na', chapter: 1 },
  { day: 328, month: 11, title: 'O Justo Viverá pela sua Fé: Oração e Louvor de Habacuc', read: 'Habacuc 1-3', bookId: 'hab', chapter: 1 },
  { day: 329, month: 11, title: 'O Dia do Senhor e o Cântico de Júbilo da Filha de Sião', read: 'Sofonias 1-3', bookId: 'sof', chapter: 1 },
  { day: 330, month: 11, title: 'A Reconstrução do Templo e a Maior Glória da Segunda Casa', read: 'Ageu 1-2', bookId: 'ag', chapter: 1 },
  { day: 331, month: 11, title: 'Não por Força nem por Violência, mas pelo Meu Espírito', read: 'Zacarias 1-4', bookId: 'zc', chapter: 1 },
  { day: 332, month: 11, title: 'A Coroa do Renovo Sacerdotal e o Jejum Transformado em Alegria', read: 'Zacarias 5-8', bookId: 'zc', chapter: 5 },
  { day: 333, month: 11, title: 'Eis que o Teu Rei Virá a Ti Humilde e Montado num Jumentinho', read: 'Zacarias 9-11', bookId: 'zc', chapter: 9 },
  { day: 334, month: 11, title: 'Olharão para Aquele a Quem Traspassaram e Haverá uma Fonte Aberta', read: 'Zacarias 12-14', bookId: 'zc', chapter: 12 },

  // ==========================================
  // MÊS 12 (DEZEMBRO): DIAS 335 A 365
  // Malaquias (1-3) & O Cumprimento das Profecias e Esperança do Advento
  // ==========================================
  { day: 335, month: 12, title: 'O Sol da Justiça que Nasce com a Cura em suas Asas', read: 'Malaquias 1-3', bookId: 'mal', chapter: 1 },
  { day: 336, month: 12, title: 'A Genealogia Sagrada e a Anunciação a São José', read: 'São Mateus 1-2 • Salmos 121', bookId: 'mt', chapter: 1 },
  { day: 337, month: 12, title: 'O Cântico de Zacarias (Benedictus) e o Precursor João Batista', read: 'São Lucas 1, 1-56 • Salmos 122', bookId: 'lc', chapter: 1 },
  { day: 338, month: 12, title: 'O Cântico de Nossa Senhora (Magnificat): O Todo-Poderoso Fez em Mim Maravilhas', read: 'São Lucas 1, 57-80 • Salmos 123', bookId: 'lc', chapter: 1 },
  { day: 339, month: 12, title: 'O Nascimento de Jesus em Belém e a Visita dos Pastores', read: 'São Lucas 2, 1-20 • Salmos 124', bookId: 'lc', chapter: 2 },
  { day: 340, month: 12, title: 'A Apresentação no Templo e o Cântico de Simeão (Nunc Dimittis)', read: 'São Lucas 2, 21-52 • Salmos 125', bookId: 'lc', chapter: 2 },
  { day: 341, month: 12, title: 'A Luz que Brilha nas Trevas e o Verbo que se Fez Carne', read: 'São João 1, 1-18 • Salmos 126', bookId: 'joa', chapter: 1 },
  { day: 342, month: 12, title: 'As Bem-Aventuranças: O Roteiro da Santidade Cristã', read: 'São Mateus 5, 1-16 • Salmos 127', bookId: 'mt', chapter: 5 },
  { day: 343, month: 12, title: 'O Pai Nosso: A Oração Perfeita Ensinada por Jesus', read: 'São Mateus 6, 1-18 • Salmos 128', bookId: 'mt', chapter: 6 },
  { day: 344, month: 12, title: 'A Casa Construída sobre a Rocha Firme da Fé', read: 'São Mateus 7 • Salmos 129', bookId: 'mt', chapter: 7 },
  { day: 345, month: 12, title: 'A Confissão de Pedro: Tu és o Cristo, o Filho de Deus Vivo', read: 'São Mateus 16 • Salmos 130', bookId: 'mt', chapter: 16 },
  { day: 346, month: 12, title: 'A Transfiguração no Monte Tabor e a Glória Divina', read: 'São Mateus 17 • Salmos 131', bookId: 'mt', chapter: 17 },
  { day: 347, month: 12, title: 'O Bom Pastor que Busca a Ovelha Perdida', read: 'São Lucas 15 • Salmos 132', bookId: 'lc', chapter: 15 },
  { day: 348, month: 12, title: 'A Eucaristia Sagrada: Tomai e Comei, Isto é o Meu Corpo', read: 'São Lucas 22 • Salmos 133', bookId: 'lc', chapter: 22 },
  { day: 349, month: 12, title: 'O Caminho de Emaús: Reconhecido ao Partir o Pão', read: 'São Lucas 24 • Salmos 134', bookId: 'lc', chapter: 24 },
  { day: 350, month: 12, title: 'O Bom Pastor e a Vida em Abundância', read: 'São João 10 • Salmos 135', bookId: 'joa', chapter: 10 },
  { day: 351, month: 12, title: 'Eu Sou a Videira Verdadeira e Vós os Ramos', read: 'São João 15 • Salmos 136', bookId: 'joa', chapter: 15 },
  { day: 352, month: 12, title: 'A Grande Oração Sacerdotal de Jesus pela Igreja', read: 'São João 17 • Salmos 137', bookId: 'joa', chapter: 17 },
  { day: 353, month: 12, title: 'O Derramamento do Espírito Santo no Cenáculo', read: 'Atos 2 • Salmos 138', bookId: 'at', chapter: 2 },
  { day: 354, month: 12, title: 'Quem nos Separará do Amor de Cristo?', read: 'Romanos 8 • Salmos 139', bookId: 'rm', chapter: 8 },
  { day: 355, month: 12, title: 'A Caridade Nunca Falha e Permanece para Sempre', read: '1 Coríntios 13 • Salmos 140', bookId: '1cor', chapter: 13 },
  { day: 356, month: 12, title: 'O Hino da Encarnação e Humilhação de Cristo em Filipos', read: 'Filipenses 2 • Salmos 141', bookId: 'flp', chapter: 2 },
  { day: 357, month: 12, title: 'A Plenitude da Divindade que Habita em Cristo Jesus', read: 'Colossenses 1-2 • Salmos 142', bookId: 'col', chapter: 1 },
  { day: 358, month: 12, title: 'O Grande Sumo Sacerdote que Intercede por Nós', read: 'Hebreus 4-5 • Salmos 143', bookId: 'heb', chapter: 4 },
  { day: 359, month: 12, title: 'A Galeria dos Heróis da Fé e a Firme Esperança', read: 'Hebreus 11 • Salmos 144', bookId: 'heb', chapter: 11 },
  { day: 360, month: 12, title: 'A Pedra Angular Escolhida e Preciosa para Deus', read: '1 Pedro 2 • Salmos 145', bookId: '1pe', chapter: 2 },
  { day: 361, month: 12, title: 'Deus é Amor: Aquele que Permanece no Amor Permanece em Deus', read: '1 João 4 • Salmos 146', bookId: '1jo', chapter: 4 },
  { day: 362, month: 12, title: 'O Trono Celestial e o Cântico dos Anjos e Santos', read: 'Apocalipse 4-5 • Salmos 147', bookId: 'ap', chapter: 4 },
  { day: 363, month: 12, title: 'Eis que Faço Novas Todas as Coisas: A Jerusalém Celestial', read: 'Apocalipse 21 • Salmos 148', bookId: 'ap', chapter: 21 },
  { day: 364, month: 12, title: 'O Rio da Água da Vida e a Árvore que Cura as Nações', read: 'Apocalipse 22, 1-11 • Salmos 149', bookId: 'ap', chapter: 22 },
  { day: 365, month: 12, title: 'Vem, Senhor Jesus! A Graça do Senhor Esteja com Todos. Amém.', read: 'Apocalipse 22, 12-21 • Salmos 150', bookId: 'ap', chapter: 22 }
];
